import type { Metadata } from "next";
import "@/styles/globals.css";
import Header from "@/features/Header/Header";

export const metadata: Metadata = {
  title: "صندوق پژوهش و فناوری",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body dir="rtl">
        <Header />

        <main>{children}</main>

        <footer></footer>
      </body>
    </html>
  );
}
