import type { Metadata } from "next";
import "@/styles/globals.css";
import Header from "@/features/Header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#092934] xl:container xl:mx-auto" dir="rtl">
        <Header />

        <main>{children}</main>

        <footer></footer>
      </body>
    </html>
  );
}
